openapi: 3.0.0
info:
  title: API
  version: 1.0.0
paths:
  /api/v1/tasks:
    get:
      summary: Get all tasks
      responses:
        200:
          description: List all tasks
    post:
      summary: Create a new task
      responses:
        200:
          description: Task created
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - description
                - deadline
              properties:
                description:
                  type: string
                deadline:
                  type: string
                  format: date
  /api/v1/tasks/{taskId}:
    get:
      summary: List single task
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Task ID
      responses: 200
    put:
      summary: Update task
      responses:
        200:
          description: Task updated
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Task ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - description
                - deadline
              properties:
                description:
                  type: string
                deadline:
                  type: string
                  format: date
    delete:
      summary: Delete Task
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Task ID
      responses: 200
